export enum CloudEnv {
  Public = 'public',
  USBank = 'usbank',
  JPMC = 'jpmc',
  CISCO = 'cisco',
  VFTEST76 = 'vftest-76',
  VFTESTBR = 'vf-dev-br-2',
  VFTEST82 = 'vftest-82',
  GM = 'gm',
  VODAFONE = 'vodafone',
  SUPERLOOP = 'superloop',
  AMAZON = 'amazon',
  KP = 'kp',
  KEYBANK = 'keybank',
  USAA = 'usaa',
  MATTEL = 'mattel',
  REDVENTURES = 'redventures',
}
